ChasAPIBundle:
    resource: "@ChasAPIBundle/Resources/config/routing.yml"
    
chas_secured:
    resource: "@ChasAdminBundle/Controller/SecuredController.php"
    type:     annotation

ChasBannerBundle:
    resource: "@ChasBannerBundle/Resources/config/routing.yml"
    prefix:   /

ChasRouteBundle:
    resource: "@ChasRouteBundle/Resources/config/routing.yml"
    prefix:   /

ChasAdminBundle:
    resource: "@ChasAdminBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
