ChasAPIBundle:
    resource: "@ChasAPIBundle/Controller/"
    type:     annotation
    prefix:   /

ChasAdminBundle:
    resource: "@ChasAdminBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
