API_start:
    pattern:  /api/
    defaults: { _controller: ChasAPIBundle:API:welcome }
    requirements:
        _method:    GET

API_carpool_all:
    pattern:  /api/carpool.{_format}
    defaults: { _controller: ChasAPIBundle:API:carpool, _format: html }
    requirements:
        _method:    GET
        _format:    html|json|xml
API_carpool_single:
    pattern:  /api/carpool/{id}.{_format}
    defaults: { _controller: ChasAPIBundle:API:carpool_single, _format: html }
    requirements:
        _method:    GET
        _format:    html|json|xml
API_carpool_single_new:
    pattern:  /api/carpool
    defaults: { _controller: ChasAPIBundle:API:carpool_new }
    requirements:
        _method:    GET

API_weather:
    pattern:  /api/weather/{lat}/{lon}
    defaults: { _controller: ChasAPIBundle:API:weather }
    requirements:
        _method:    GET

API_all:
    pattern:  /api/timetable/{resource}.{_format}
    defaults: { _controller: ChasAPIBundle:API:index, _format: html }
    requirements:
        _method:    GET
        _format:    html|json|xml
API_single:
    pattern:  /api/timetable/{resource}/{id}.{_format}
    defaults: { _controller: ChasAPIBundle:API:single, _format: html }
    requirements:
        id:         \d+
        _method:    GET
        _format:    html|json|xml
API_timetable_trip:
    pattern:  /api/timetable/{resource}/{from}/{to}/{when}.{_format}
    defaults: { _controller: ChasAPIBundle:API:trip, _format: html }
    requirements:
        _method:    GET
        _format:    html|json|xml


API_page:
    pattern:  /api/page.{_format}
    defaults: { _controller: ChasAPIBundle:API:page, _format: html }
    requirements:
        _method:    GET
        _format:    html|json|xml
API_page_single:
    pattern:  /api/page/{id}.{_format}
    defaults: { _controller: ChasAPIBundle:API:pageSingle, _format: html }
    requirements:
        _method:    GET
        _format:    html|json|xml
