ChasAdminBundle_homepage:
    pattern:        /admin
    defaults:       { _controller: ChasAdminBundle:Default:index }

ChasAdminBundle_page:
    pattern:        /secured/page
    defaults:       { _controller: ChasAdminBundle:Page:page }
ChasAdminBundle_page_new:
    pattern:        /secured/page/new
    defaults:       { _controller: ChasAdminBundle:Page:pageNew }
ChasAdminBundle_page_update:
    pattern:        /secured/page/{id}
    defaults:       { _controller: ChasAdminBundle:Page:pageUpdate }


ChasAdminBundle_route:
    pattern:        /secured/route
    defaults:       { _controller: ChasRouteBundle:Route:route }
ChasAdminBundle_route_new:
    pattern:        /secured/route/new
    defaults:       { _controller: ChasRouteBundle:Route:new }
ChasAdminBundle_route_remove:
    pattern:        /secured/route/{id}/remove
    defaults:       { _controller: ChasRouteBundle:Route:remove }



ChasAdminBundle_banner:
    pattern:        /secured/banner
    defaults:       { _controller: ChasAdminBundle:Banner:banner }
ChasAdminBundle_banner_new:
    pattern:        /secured/banner/new
    defaults:       { _controller: ChasAdminBundle:Banner:bannerNew }
ChasAdminBundle_banner_update:
    pattern:        /secured/banner/{id}
    defaults:       { _controller: ChasAdminBundle:Banner:bannerUpdate }
ChasAdminBundle_banner_remove:
    pattern:        /secured/banner/{id}/remove
    defaults:       { _controller: ChasAdminBundle:Banner:bannerRemove }

ChasAdminBundle_carpool:
    pattern:        /secured/carpool
    defaults:       { _controller: ChasAdminBundle:CarPool:carpool }
ChasAdminBundle_carpool_remove:
    pattern:        /secured/carpool/{id}/remove
    defaults:       { _controller: ChasAdminBundle:CarPool:remove }
