parameters:
#    chas_admin.example.class: Chas\AdminBundle\Example

services:
#    chas_admin.example:
#        class: %chas_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
